<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>api_documentation</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <style>
            body{
                background-color:black;
                margin:30px;
            }
            .group{
                color:gray;
                padding:50px;
                font-size:1em;
                padding:15px;
            }
        </style>
        <!-- Latest compiled and minified CSS -->
        <!--<link rel="stylesheet" href="<?=""?>bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">-->
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->



        <div class="container" style="background-color:white;">
            
            
            <div class="group">
                <h5>API (ALL API's)</h5>
                <table border="0">
                    <tr style="background-color:orange;color:black;">
                        <td>Name</td><td>URL</td><td>DOC</td><td>METHOD</td>
                    </tr>
                    <?php for($i = 0; $i<sizeof($all);$i++){?>
                        <tr>
                            <td><?=$all[$i]['name']?></td>
                            <td><?=$all[$i]['url']?></td>
                            <td><?=$all[$i]['doc']?></td>
                            <td><?=$all[$i]['method']?></td>
                        </tr>
                    <?php }?>
                </table>
            </div>

         
            




        </div>


        
        <!--<script src="<?= "" ?>"></script>-->
        <script>


            var $RAW_DATA = '<?= json_encode($data)?>';//read from php array
            var $DATA = JSON.parse($RAW_DATA);
            console.log("data-" + $DATA.length);
            //alert($RAW_DATA);


        </script>
    </body>
</html>