<!DOCTYPE html>
<head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>test</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body style="margin-left:400px;margin-right:400px;margin-top:350px;">
        <center><h1>Hello there<?php echo "---";?></h1></center>
    </body>
</html>